---
default:
  image: docker:24.0
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

variables:
  TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

build:
  stage: build
  script:
    - docker build --pull -t $TEST_IMAGE .
    - docker push $TEST_IMAGE

lint:
  stage: test
  image: $TEST_IMAGE
  script:
    - pre-commit run --all-files

release:
  stage: deploy
  only:
    - tags
  script:
    - docker pull $TEST_IMAGE
    - docker tag $TEST_IMAGE $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker tag $TEST_IMAGE $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE --all-tags
